name: Deploy Tetris Application
on:
  push:
    branches:
      - dev

  # workflow_dispatch:
  #   inputs:
  #     branch:
  #       description: "Branch to deploy from"
  #       required: true
  #       default: "dev"

jobs:
  validate-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Docker, NGINX, and Certbot Installation
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: azureadmin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Checking Docker installation..."
            sudo systemctl status docker > /dev/null && echo "Docker is installed and running." || { echo "Docker is not running."; exit 1; }

            echo "Checking NGINX installation..."
            sudo systemctl status nginx > /dev/null && echo "NGINX is installed and running." || { echo "NGINX is not running."; exit 1; }

            echo "Checking Certbot installation..."
            certbot --version > /dev/null && echo "Certbot is installed." || { echo "Certbot is not installed."; exit 1; }
            echo "All validations passed."

  scan-docker-image:
    runs-on: ubuntu-latest
    needs: validate-environment
    steps:
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: sajid79/tetris-js-app:amd64
          format: table
          severity: HIGH,CRITICAL

  deploy-docker-image:
    runs-on: ubuntu-latest
    needs: scan-docker-image
    steps:
      - name: Deploy Docker Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: azureadmin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Set user permissions for Docker..."
            sudo usermod -aG docker azureadmin

            if ! docker ps | grep -q "sajid79/tetris-js-app:amd64"; then
              echo "Pulling and running the Docker container..."
              docker pull sajid79/tetris-js-app:amd64
              docker run -d -p 8080:80 sajid79/tetris-js-app:amd64
              sleep 10
            else
              echo "Docker container is already running."
            fi
            docker ps

  verify-deployment:
    runs-on: ubuntu-latest
    needs: deploy-docker-image
    steps:
      - name: Verify Application Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: azureadmin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Verifying application on https://tetris.sohailsajid.dev"
            curl -I https://tetris.sohailsajid.dev || {
              echo "Deployment verification failed!"
              exit 1
            }
            echo "Application successfully deployed."

  create-pr:
    runs-on: ubuntu-latest
    needs: verify-deployment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch: dev
          base: main
          commit-message: "automated PR"
          title: "Deploy Tetris Application"
          body: |
            This PR merges deployment changes for the dev branch into the main branch.
